-- -- go to end of file
-- vim.keymap.set("n", "<C-f>", "<C-f>zz",
--   { desc = "Move down half a screen and stay centered" })
--
-- -- go to beginning of file
-- vim.keymap.set("n", "<C-b>", "<C-b>zz",
--   { desc = "Move up half a screen and stay centered" })
--
-- local map = function(type, key, value)
--   vim.fn.nvim_buf_set_keymap(0, type, key, value, { noremap = true, silent = true });
-- end
--
-- vim.keymap.set("x", "<leader>p", "\"_dP")
